### ISSUE TITLE
always get Invalid solution while running your example code

### ISSUE THREAD

**Issue by andreas83** [altcha-org/altcha-lib-php#1]
Not sure why, but when i run your basic example from readme, i always get Invalid solution.  

```
Challenge created: {"algorithm":"SHA-256","challenge":"d8afaf9fd910d01c0ef6369b044cbb533071d204244ff9e4b96ce524c89d0a54","maxnumber":50000,"salt":"50cbc548da9f46b84083b67f","signature":"7ce8c30030426e900550db3d81448116673cf7796b94ba1d627364bd1c43a275"}
Invalid solution.
```

Tried with PHP 7.4 , 8.2 and 8.4

**Comment by andreas83** [comment]
Looks like i fixed myself ( with a hint of ai) 
seems like the number variable is not very optional (as the readme may suggest) 

```
<?php
use AltchaOrg\Altcha\ChallengeOptions;
use AltchaOrg\Altcha\Altcha;

$hmacKey = 'secret hmac key';

// Generate a random number within the range
$number = rand(0, 50000);
echo "Generated number: " . $number . "\n";

// Create a new challenge with the generated number
$options = new ChallengeOptions([
    'hmacKey'   => $hmacKey,
    'maxNumber' => 50000, // the maximum random number
    'number'    => $number, // Pass the generated number
]);

$challenge = Altcha::createChallenge($options);
echo "Challenge created: " . json_encode($challenge) . "\n";

// Example payload to verify
$payload = [
    'algorithm' => $challenge->algorithm,
    'challenge' => $challenge->challenge,
    'number'    => $number, // Use the generated number
    'salt'      => $challenge->salt,
    'signature' => $challenge->signature,
];

echo "Payload: " . json_encode($payload) . "\n";

// Verify the solution
$ok = Altcha::verifySolution($payload, $hmacKey, true);

if ($ok) {
    echo "Solution verified!\n";
} else {
    echo "Invalid solution.\n";
}
?>



```

**Comment by ovx** [comment]
Hi, the `number` attribute is optional, if not provided, a random number will be generated for the challenge.
The function `verifySolution` verifies the solution (not the challenge), to find the solution (the random secret number), you need to solve the challenge with the widget of use the `solveChallenge` function.
 
The example includes only an example number, which you're supposed to get from the widget or the `solveChallenge` function. To make the example code work without solving the challenge, you can manually generate the number as you mentioned.

For more information, refer to the [PoW docs](https://altcha.org/docs/proof-of-work/).

**Comment by andreas83** [comment]
thanks for clarification
