### ISSUE TITLE
i am not able implement altcha in wordpress login from 

### ISSUE THREAD

**Issue by roshanoneloop** [altcha-org/altcha-lib-php#2]
<?php
/**
 * Handle login UI frontend.
 */
namespace Advanced_Login_Page_Customizer;

defined( 'ABSPATH' ) || exit;

class Altcha_CAPTCHA {
    public static $handle = 'alpc-public-captcha';

    private static $altcha_site_key = 'key_1jij74aeuCcKmnHPnwJ9C';
    private static $altcha_secret_key = 'b9c9e2c4895c2d6ab2a692ba';

    /**
     * Initialize class.
     */
    public static function init() {
        add_action( 'login_enqueue_scripts', array( __CLASS__, 'register_assets' ), 11 );
        add_action( 'login_enqueue_scripts', array( __CLASS__, 'enqueue_scripts' ) );

        // CAPTCHA related actions and filters.
        add_action( 'login_form', array( __CLASS__, 'add_altcha_to_login_form' ) );
        add_filter( 'wp_authenticate_user', array( __CLASS__, 'verify_altcha_on_login' ), 10, 2 );
        add_filter( 'login_body_class', array( __CLASS__, 'login_body_class' ) );
         self::load_altcha_keys();
          // Modify the script tag to include the "type" attribute
    add_filter( 'script_loader_tag', function( $tag, $handle ) {
        if ( 'alpc-altcha' === $handle ) {
            $tag = str_replace('src=', 'type="module" src=', $tag);
        }
        return $tag;
    }, 10, 2 );
    }
    /**
     * Load Altcha keys from settings.
     */
    public static function load_altcha_keys() {
        // Normally, you would load from options, but using hardcoded keys for this example
        self::$altcha_site_key = 'key_1jij74aeuCcKmnHPnwJ9C';
        self::$altcha_secret_key = 'b9c9e2c4895c2d6ab2a692ba';
        // error_log('site key: ' . self::$altcha_site_key);
        // error_log('secret key: ' . self::$altcha_secret_key);
    }

    /**
     * Register assets.
     */
    public static function register_assets() {
        $asset_file_values = include_once 'index.asset.php';
        $deps = $asset_file_values['dependencies'];
        $ver = $asset_file_values['version'];
        $src = sprintf( '%sbuild/non-blocks/public/captcha/index.js', ADVANCED_LOGIN_PAGE_CUSTOMIZER_CAPTCHA_BASE_URL );

        wp_register_script( self::$handle, $src, $deps, $ver, true );
        wp_register_style( self::$handle, sprintf( '%sbuild/non-blocks/public/captcha/index.css', ADVANCED_LOGIN_PAGE_CUSTOMIZER_CAPTCHA_BASE_URL ), array(), $ver );
    }

    /**
     * Enqueue Altcha scripts.
     */
    public static function enqueue_scripts() {
        if ( empty( self::$altcha_site_key ) || empty( self::$altcha_secret_key ) ) {
            return;
        }

        wp_enqueue_script( self::$handle );
        wp_enqueue_style( self::$handle );

        //.Altcha API script
        wp_enqueue_script( 'alpc-altcha', 'https://eu.altcha.org/js/latest/altcha.min.js', array(), null, true );
       
    }

    /**
     * Add Altcha to login form.
     */
   public static function add_altcha_to_login_form() {
    if ( empty( self::$altcha_site_key ) || empty( self::$altcha_secret_key ) ) {
       error_log('Altcha keys are not set.');
        return;
    }

    // Render the Altcha CAPTCHA container
    echo '<div id="altcha-container" class="alpc-altcha" data-sitekey="' . esc_attr( self::$altcha_site_key ) . '" style="z-index: 1000; position: relative;"></div>';
	// echo '<script src="https://eu.altcha.org/js/latest/altcha.min.js" ></script>';

    ?>
     <script>
            console.log('Site Key:', '<?php echo esc_js(self::$altcha_site_key); ?>');

            document.addEventListener('DOMContentLoaded', function() {
                if (typeof altcha === 'undefined') {
                    console.error('Altcha script is not loaded.');
                    return;
                }

                const loginForm = document.getElementById('loginform');

                // Define the callback for Altcha
                window.altchaCallback = function(token) {
                    const loginForm = document.getElementById('loginform');
                    let altchaResponse = document.createElement('input');
                    altchaResponse.setAttribute('type', 'hidden');
                    altchaResponse.setAttribute('name', 'altcha-response');
                    altchaResponse.setAttribute('value', token);
                    loginForm.appendChild(altchaResponse);
                    loginForm.submit(); // Submit the form after adding the token
                };
                console.log('loginForm:', loginForm);
                console.log('altcha:', altchaCallback);
                console.log('altcha:', altcha);

                if (loginForm) {
                    loginForm.addEventListener('submit', function(event) {
                        event.preventDefault(); // Prevent default form submission until Altcha is executed

                        if (typeof altcha !== 'undefined') {
                            altcha.ready(function() {
								console.log('Altcha ready');
                                altcha.execute('altcha-container', 'altchaCallback');
                            });
                        } else {
                            console.error('Altcha script is not loaded.');
                        }
                    });
                }
            });
        </script>
    <?php
}

    /**
     * Verify Altcha on login.
     */
    public static function verify_altcha_on_login( $user, $username ) {
        if ( is_wp_error( $user ) ) {
            return $user;
        }

        if ( empty( self::$altcha_site_key ) || empty( self::$altcha_secret_key ) ) {
            error_log('Altcha keys are not set.');
            return $user;
        }

        // Ensure the response exists
        if ( empty( $_POST['altcha-response'] ) ) {
            return new \WP_Error( 'captcha_error', __( 'Please complete the Altcha challenge.', 'advanced-login-page-customizer' ) );
        }

        // Send a verification request to Altcha
        $response = wp_remote_post( 'https://eu.altcha.org/verify', array(
            'body' => array(
                'secret'   => self::$altcha_secret_key,
                'response' => sanitize_text_field( $_POST['altcha-response'] ),
            ),
        ));

        if ( is_wp_error( $response ) ) {
            return new \WP_Error( 'captcha_error', __( 'Error in verifying Altcha. Please try again later.', 'advanced-login-page-customizer' ) );
        }

        $response_body = json_decode( wp_remote_retrieve_body( $response ), true );
        error_log( 'Altcha verification response: ' . print_r( $response_body, true ) );

        if ( ! isset( $response_body['success'] ) || ! $response_body['success'] ) {
            return new \WP_Error( 'captcha_error', __( 'Altcha verification failed. Please try again.', 'advanced-login-page-customizer' ) );
        }

        return $user;
    }

    /**
     * Add custom body class if Altcha is active.
     */
    public static function login_body_class( $classes ) {
        if ( empty( self::$altcha_site_key ) || empty( self::$altcha_secret_key ) ) {
            return $classes;
        }
        $classes[] = 'alpc-altcha-enabled';
        return $classes;
    }
}

// Initialize the Altcha_CAPTCHA class.
Altcha_CAPTCHA::init();

**Comment by ovx** [comment]
Hi, I recommend using the official Wordpress plugin:

- https://wordpress.org/plugins/altcha-spam-protection/
- https://github.com/altcha-org/wordpress-plugin

It allows you to turn on ALTCHA on the Wordpress login page and other pages.

**Comment by roshanoneloop** [comment]
using plugin the altcha widget is appering but the verify buffering is taking long long time and i am not able to login

**Comment by ovx** [comment]
If it takes long, you can try to log-in on a more powerful device and change the "Complexity" to "low" after logging in.

**Comment by roshanoneloop** [comment]
how can i code customly to add altcha in wp login form without using plugin 
thank you for your kind response
