### ISSUE TITLE
I need some help with tutorial

### ISSUE THREAD

**Issue by NadudvariT** [altcha-org/altcha-lib-php#3]
Hey,
I tried to create a super simple script to test Altcha, but I don't get it what's wrong. Challenge appears, but I got an error constantly.

I created a few lines of html:
![kép](https://github.com/user-attachments/assets/a8cbf185-eb08-4520-bbf9-ea5bcbd7a64f)

And I put the example code into challenge php:
![kép](https://github.com/user-attachments/assets/2e457bd3-3e2e-4dd1-88b8-f830490d1629)

**Comment by ovx** [comment]
Hi, what error are you getting? You can enable debug mode to see more information (https://altcha.org/docs/troubleshooting/). One common issues is that you're running the website in non-secure context (without HTTPS) (https://altcha.org/docs/website-integration/#caveats).

**Comment by NadudvariT** [comment]
Hi, thanks your help. I started testing on localhost, I moved to https domain. I truned on debug but I still can't figure out the problem. If you can check my url I would appreciate it: https://weblovag.hu/altcha/alcha.php
Files has the same content as the screenshot.

**Comment by NadudvariT** [comment]
Thanks, I solved and reworked. I leave this example here for anyone who wants a simple PHP test in the future.

HTML:
![image](https://github.com/user-attachments/assets/73862d4a-1236-422c-9339-75411eaa656c)

Challenge.php:
![image](https://github.com/user-attachments/assets/5310593c-4852-4f01-b41e-a0db1f03355a)

Submit.php:
![image](https://github.com/user-attachments/assets/f0d82a99-6b0f-4186-932c-ba9615142167)
